int d=50;
int d1=100;

void setup()
{
  pinMode(2, OUTPUT);
  pinMode(3, OUTPUT);
  pinMode(4, OUTPUT);
  pinMode(5, OUTPUT);
  pinMode(A1, OUTPUT);
  pinMode(A0, OUTPUT);
}
void loop()
{
    digitalWrite(A0, HIGH);
    delay(d);
    digitalWrite(A1, LOW);
    delay(d);
    digitalWrite(2, HIGH);
    delay(d); 
    digitalWrite(2, HIGH);
    delay(d);
    digitalWrite(A0, HIGH);
    delay(d);
    digitalWrite(A1, LOW);
    delay(d);
    digitalWrite(3, HIGH);
    delay(d);
    digitalWrite(3, HIGH);
    delay(d);
    digitalWrite(A0, HIGH);
    delay(d);
    digitalWrite(A1, LOW);
    delay(d);
    digitalWrite(4, HIGH);
    delay(d);
    digitalWrite(4, HIGH);
    delay(d);
    digitalWrite(A0, HIGH);
    delay(d);
    digitalWrite(A1, LOW);
    delay(d);
    digitalWrite(5, HIGH);
    delay(d);
    digitalWrite(5, HIGH);
    delay(d);
    digitalWrite(A0, HIGH);
    delay(d);
    digitalWrite(A1, LOW);
    delay(d);
    delay(d1);
    digitalWrite(A0, LOW);
    delay(d);
    digitalWrite(A1, HIGH);
    delay(d);
    digitalWrite(2, HIGH);
    delay(d); 
    digitalWrite(2, HIGH);
    delay(d);
    digitalWrite(A0, LOW);
    delay(d);
    digitalWrite(A1, HIGH);
    delay(d);
    digitalWrite(3, HIGH);
    delay(d);
    digitalWrite(3, HIGH);
    delay(d);
    digitalWrite(A0, LOW);
    delay(d);
    digitalWrite(A1, HIGH);
    delay(d);
    digitalWrite(4, HIGH);
    delay(d);
    digitalWrite(4, HIGH);
    delay(d);
    digitalWrite(A0, LOW);
    delay(d);
    digitalWrite(A1, HIGH);
    delay(d);
    digitalWrite(5, HIGH);
    delay(d);
    digitalWrite(5, HIGH);
    delay(d);
    digitalWrite(A0, LOW);
    delay(d);
    digitalWrite(A1, HIGH);
    delay(d);
    delay(d1);
    digitalWrite(A0, HIGH);
    delay(d);
    digitalWrite(A1, LOW);
    delay(d);
    digitalWrite(2, HIGH);
    delay(d); 
    digitalWrite(2, LOW);
    delay(d);
    digitalWrite(A0, HIGH);
    delay(d);
    digitalWrite(A1, LOW);
    delay(d);
    digitalWrite(3, HIGH);
    delay(d);
    digitalWrite(3, LOW);
    delay(d);
    digitalWrite(A0, HIGH);
    delay(d);
    digitalWrite(A1, LOW);
    delay(d);
    digitalWrite(4, HIGH);
    delay(d);
    digitalWrite(4, LOW);
    delay(d);
    digitalWrite(A0, HIGH);
    delay(d);
    digitalWrite(A1, LOW);
    delay(d);
    digitalWrite(5, HIGH);
    delay(d);
    digitalWrite(5, LOW);
    delay(d);
    digitalWrite(A0, HIGH);
    delay(d);
    digitalWrite(A1, LOW);
    delay(d);
    delay(d1);
    digitalWrite(A0, LOW);
    delay(d);
    digitalWrite(A1, HIGH);
    delay(d);
    digitalWrite(2, HIGH);
    delay(d); 
    digitalWrite(2, LOW);
    delay(d);
    digitalWrite(A0, LOW);
    delay(d);
    digitalWrite(A1, HIGH);
    delay(d);
    digitalWrite(3, HIGH);
    delay(d);
    digitalWrite(3, LOW);
    delay(d);
    digitalWrite(A0, LOW);
    delay(d);
    digitalWrite(A1, HIGH);
    delay(d);
    digitalWrite(4, HIGH);
    delay(d);
    digitalWrite(4, LOW);
    delay(d);
    digitalWrite(A0, LOW);
    delay(d);
    digitalWrite(A1, HIGH);
    delay(d);
    digitalWrite(5, HIGH);
    delay(d);
    digitalWrite(5, LOW);
    delay(d);
    digitalWrite(A0, LOW);
    delay(d);
    digitalWrite(A1, HIGH);
    delay(d);
    delay(d1);
    digitalWrite(A0, LOW);
    delay(d);
    digitalWrite(A1, LOW);
    delay(d);
    digitalWrite(2, HIGH);
    delay(d); 
    digitalWrite(2, HIGH);
    delay(d);
    digitalWrite(A0, LOW);
    delay(d);
    digitalWrite(A1, LOW);
    delay(d);
    digitalWrite(3, HIGH);
    delay(d);
    digitalWrite(3, HIGH);
    delay(d);
    digitalWrite(A0, LOW);
    delay(d);
    digitalWrite(A1, LOW);
    delay(d);
    digitalWrite(4, HIGH);
    delay(d);
    digitalWrite(4, HIGH);
    delay(d);
    digitalWrite(A0, LOW);
    delay(d);
    digitalWrite(A1, LOW);
    delay(d);
    digitalWrite(5, HIGH);
    delay(d);
    digitalWrite(5, HIGH);
    delay(d);
    digitalWrite(A0, LOW);
    delay(d);
    digitalWrite(A1, LOW);
    delay(d);
    delay(d1);
}
